name: Signal K
highlighter: rouge
kramdown:
  input: GFM
collections:
  api:
    output: true
  developers:
    output: true
gems:
  - jekyll-mentions
  - jekyll-sitemap
url:
baseurl:
logo: /images/signalk.gif
