name: Signal K
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
collections:
  api:
    output: true
  developers:
    output: true
gems:
  - jekyll-mentions
  - jekyll-sitemap
baseurl:
