name: Signal K
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
asciidoc: asciidoctor
asciidoc_ext: ad,adoc,asciidoc
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=class
    - pygments-style=perldoc
gems:
  - jekyll-mentions
baseurl:
